spring:
  application: hello
  profiles:
    active:
  #视图配置
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  #数据源配置(在Spring Boot1.4.0中驱动配置信息没有问题，但是连接池的配置信息不再支持这里的配置项，即无法通过配置)
  #参考链接：http://blog.csdn.net/blueheart20/article/details/52384032
  datasource:
    # 驱动配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
    #连接池的配置信息
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
---
#容器配置
server:
  prot: 80
---
debug: true

---

